replace arch package files with a convenience script

diff --git a/.hack/linux/pkgbuild/arch-install.sh.tmpl b/.hack/linux/pkgbuild/arch-install.sh.tmpl
--- a/.hack/linux/pkgbuild/arch-install.sh.tmpl
+++ b/.hack/linux/pkgbuild/arch-install.sh.tmpl
@@ -1,10 +1,21 @@
+#!/usr/bin/env bash
+
+PKGBUILD_DIR=$(mktemp -d)
+trap 'rm -rf "$PKGBUILD_DIR"' EXIT
+
+[ -d "$PKGBUILD_DIR" ] && cd "$PKGBUILD_DIR" || {
+  echo "failed to initialize temporary directory"
+  exit 1
+}
+
+cat <<'EOF' > PKGBUILD
 # Maintainer: kasimeka
 pkgname=bromomethane
 pkgver=@version@
 pkgrel=1
 pkgdesc="A mod manager for Balatro - easily install and manage mods for the popular roguelike deckbuilding game. (none)"
 arch=('x86_64')
-url=""
+url="https://github.com/kasimeka/bromomethane"
 license=('GPL-3.0-only')
 groups=()
 depends=('cairo' 'desktop-file-utils' 'gdk-pixbuf2' 'glib2' 'gtk3' 'hicolor-icon-theme' 'libsoup3' 'openssl' 'pango' 'webkit2gtk-4.1')
@@ -16,3 +27,22 @@ sha512sums_x86_64=('@sha512sum@')
 package(){
 	tar -xz -f data.tar.gz -C "${pkgdir}"
 }
+EOF
+
+cat <<'EOF' > bromomethane.install
+post_install() {
+	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
+	update-desktop-database -q
+}
+
+post_upgrade() {
+	post_install
+}
+
+post_remove() {
+	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
+	update-desktop-database -q
+}
+EOF
+
+makepkg -sci
